# base path for api
rest.base-path=api
server.port=8088

# Monitoring endpoint
management.endpoints.web.base-path=/monitoring
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info

# data source for analytics data
spring.datasource.hikari.connection-timeout=10000
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/analytics}
spring.datasource.username=${DB_USERNAME:analytics}
spring.datasource.password=${DB_PASSWORD:analytics}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# how often shall data be transfered?
app.update_interval=15m

# lookup window to match 15 minute intervall
app.lookback_duration=1m

# DAVe endpoint
app.dave.url=http://localhost:8080/detector/save-latest-detections

# central mapping file
app.mapping=classpath:sampleMapping.json
app.mapping.intersection=classpath:defaultIntersectionMapping.json

# mapping with local file
#app.mapping=file:./Mapping-local.json
#app.mapping.intersection=file:./defaultIntersectionMapping.json

# if true adapter gets auth token for requests to DAVe 
app.auth.enabled=true

# Config to access protected DAVe instance
spring.security.oauth2.client.registration.daveclient.provider=daveprovider
spring.security.oauth2.client.registration.daveclient.client-id=client_id
spring.security.oauth2.client.registration.daveclient.client-secret=secret
spring.security.oauth2.client.registration.daveclient.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.daveclient.scope=openid, profile, email
spring.security.oauth2.client.provider.daveprovider.token-uri=https://uri

# debug security/auth
logging.level.org.springframework.security=INFO
# debug adapter functions
logging.level.de.starwit=INFO